apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-upload-claim
  namespace: firefly-iii
  labels:
    app: firefly-iii
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi